"""empty message

Revision ID: 2d8037a3ff8a
Revises: 
Create Date: 2018-09-02 11:07:20.161502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8037a3ff8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=40), nullable=False),
    sa.Column('placa', sa.String(length=8), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('renavam', sa.BigInteger(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('frota', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa'),
    sa.UniqueConstraint('renavam')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('cpf_cnpj', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('alugar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carro', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.Column('checkin', sa.DateTime(), nullable=True),
    sa.Column('checkout', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carro'], ['carro.id'], ),
    sa.ForeignKeyConstraint(['cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alugar')
    op.drop_table('cliente')
    op.drop_table('carro')
    op.drop_table('admin')
    # ### end Alembic commands ###
